// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-appointments.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-appointments.ts
var list_appointments_default = defineTool({
  name: "list_appointments",
  title: "Afspraken bekijken",
  description: "List appointments of the signed-in salon for a date or date range (YYYY-MM-DD), including customer, service and status.",
  inputSchema: {
    from: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Start date, YYYY-MM-DD."),
    to: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("End date, YYYY-MM-DD. Defaults to the start date."),
    status: z.string().optional().describe("Optional status filter, e.g. gepland or geannuleerd."),
    limit: z.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("appointments").select(
      "id, appointment_date, start_time, end_time, status, confirmation_status, price, payment_status, notes, customers(name, phone, email), services(name, duration_minutes)"
    ).gte("appointment_date", from).lte("appointment_date", to ?? from).order("appointment_date", { ascending: true }).order("start_time", { ascending: true }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { appointments: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/search-customers.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var search_customers_default = defineTool2({
  name: "search_customers",
  title: "Klanten zoeken",
  description: "Search the salon's customers by name, email or phone. Returns loyalty, VIP status, no-show and cancellation counts.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Search term matched against name, email and phone."),
    limit: z2.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const term = query.replace(/[%,]/g, " ").trim();
    const { data, error } = await supabase.from("customers").select(
      "id, name, email, phone, is_vip, loyalty_points, total_spent, no_show_count, cancellation_count, preferred_language"
    ).or(`name.ilike.%${term}%,email.ilike.%${term}%,phone.ilike.%${term}%`).order("total_spent", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { customers: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_services_default = defineTool3({
  name: "list_services",
  title: "Behandelingen bekijken",
  description: "List the salon's treatments with duration, price and whether they are bookable online.",
  inputSchema: {
    only_active: z3.boolean().default(true).describe("Only return active treatments."),
    limit: z3.number().int().min(1).max(200).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("services").select("id, name, category, duration_minutes, price, is_active, is_online_bookable, description").order("name", { ascending: true }).limit(limit ?? 100);
    if (only_active !== false) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { services: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/revenue-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var revenue_summary_default = defineTool4({
  name: "revenue_summary",
  title: "Omzet samenvatting",
  description: "Summarize paid revenue of the salon over a date range: total amount, payment count and a breakdown per payment method.",
  inputSchema: {
    from: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Start date, YYYY-MM-DD."),
    to: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("End date, YYYY-MM-DD (inclusive).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("payments").select("amount, currency, method, payment_method, status, paid_at, created_at").eq("status", "paid").gte("created_at", `${from}T00:00:00`).lte("created_at", `${to}T23:59:59`).limit(5e3);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const total = rows.reduce((sum, r) => sum + Number(r.amount ?? 0), 0);
    const byMethod = {};
    for (const r of rows) {
      const key = r.payment_method || r.method || "onbekend";
      byMethod[key] ??= { count: 0, amount: 0 };
      byMethod[key].count += 1;
      byMethod[key].amount += Number(r.amount ?? 0);
    }
    const summary = { from, to, total_amount: Number(total.toFixed(2)), payment_count: rows.length, by_method: byMethod };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/create-customer.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var create_customer_default = defineTool5({
  name: "create_customer",
  title: "Klant aanmaken",
  description: "Create a new customer record for the signed-in salon.",
  inputSchema: {
    name: z5.string().trim().min(1).describe("Full name of the customer."),
    email: z5.string().trim().email().optional(),
    phone: z5.string().trim().min(4).optional(),
    notes: z5.string().trim().optional(),
    preferred_language: z5.enum(["nl", "en", "de", "fr", "es"]).default("nl")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ name, email, phone, notes, preferred_language }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("customers").insert({
      user_id: ctx.getUserId(),
      name,
      email: email ?? null,
      phone: phone ?? null,
      notes: notes ?? null,
      preferred_language: preferred_language ?? "nl"
    }).select("id, name, email, phone, preferred_language").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Klant aangemaakt: ${data.name} (${data.id})` }],
      structuredContent: { customer: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ueqhckkuuwdsrjrdczbb";
var mcp_default = defineMcp({
  name: "glowsuite-your-salon-s-smart-system",
  title: "GlowSuite: Your Salon's Smart System",
  version: "0.1.0",
  instructions: "Tools for GlowSuite, a salon management system. Use `list_appointments` for the agenda, `search_customers` to look up clients, `list_services` for treatments and prices, `revenue_summary` for paid revenue over a period, and `create_customer` to add a new client. All data is scoped to the signed-in salon.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_appointments_default,
    search_customers_default,
    list_services_default,
    revenue_summary_default,
    create_customer_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
